config/routes.rb
DvdCatalog::Application.routes.draw do

  root :to => "movies#index"

  resources :movies do
    resources :actors
    resources :directors
    get :auto_complete_search, :on => :collection
  end

  resources :actors
  resources :directors
end

app/models/actor.rb
class Actor < Person
  attr_accessible :roles_attributes

  has_many :roles , :dependent => :destroy
  has_many :movies, :through => :roles

  accepts_nested_attributes_for :roles, :allow_destroy => true
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @actors }
    end
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
    @actor = Actor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/new
  # GET /actors/new.json
  def new
    @actor = Actor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @actor }
    end
  end

  # GET /actors/1/edit
  def edit
    @actor = Actor.find(params[:id])
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(params[:actor])

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render json: @actor, status: :created, location: @actor }
      else
        format.html { render action: "new" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /actors/1
  # PUT /actors/1.json
  def update
    @actor = Actor.find(params[:id])

    respond_to do |format|
      if @actor.update_attributes(params[:actor])
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy

    respond_to do |format|
      format.html { redirect_to actors_url }
      format.json { head :no_content }
    end
  end
end

app/views/actors/_form.erb
<%= nested_form_for @actor, :html => { :class => "form-horizontal" }  do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation" class="alert alert-block">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.date_select :birth_date, :start_year => 1900 %>
  </div>
  <div class="field">
    <%= f.label :gender%><br />
    <%= f.select :gender, Person::VALID_GENDERS.map {|k,v| [v,k]}, :include_blank => 'Select' %>
  </div>

  <div class="field">
    <%= f.label :movie_id %>
    <%= f.fields_for :roles do |movie_form| %>
      <%= movie_form.select :movie_id, Movie.all.map { |d| [d.name, d.id] }, :include_blank => 'Select a movie' %>
      <%= movie_form.link_to_remove "Remove this movie" , :class => "btn btn-mini btn-danger" %>
    <% end %>
    </br>
    <%= f.link_to_add "Add a movie", :roles , :class => "btn btn-mini" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/create.html.erb
<h1>Directors#create</h1>
<p>Find me in app/views/directors/create.html.erb</p>

app/views/actors/destroy.html.erb
<h1>Directors#destroy</h1>
<p>Find me in app/views/directors/destroy.html.erb</p>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<h1>Listing actors</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @actors.each do |actor| %>
  <tr>
    <td><%= actor.name %></td>
    <td><%= actor.birth_date %></td>
    <td><%= actor.gender_humanize %></td>
    <td><%= link_to 'Show', actor %></td>
    <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
    <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New actor', new_actor_path , :class => "btn btn-large btn-primary disabled" %>

app/views/actors/new.html.erb
<h1>New director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/actors/show.html.erb
<div id="notice" ><%= notice %></div>

  <p>
    <b>Name:</b>
    <%= @actor.name %>
  </p>

  <p>
    <b>Birth date:</b>
    <%= @actor.birth_date %>
  </p>

  <p>
    <b>Gender:</b>
    <%= @actor.gender_humanize %>
  </p>

  <% if @actor.movies.any? %>
    <p>
      <b>Movies:</b>
      <ul>
        <% @actor.movies.each do |movie| %>
          <li><%= link_to movie.name, movie %></li>
        <% end %>
      </ul>
    </p>
  <% end %>

<%= link_to 'Edit', edit_actor_path(@actor), :class => "btn btn-large"  %>
<%= link_to 'Back', actors_path, :class => "btn btn-large"  %>