config/routes.rb
DvdCatalog::Application.routes.draw do

  root :to => "movies#index"

  resources :movies do
    resources :actors
    resources :directors
    get :auto_complete_search, :on => :collection
  end

  resources :actors
  resources :directors
end

app/models/director.rb
class Director < Person
  attr_accessible :movies_attributes, :movies

  has_many :movies

  accepts_nested_attributes_for :movies
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @directors }
    end
  end

  # GET /directors/1
  # GET /directors/1.json
  def show
    @director = Director.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/new
  # GET /directors/new.json
  def new
    @director = Director.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @director }
    end
  end

  # GET /directors/1/edit
  def edit
    @director = Director.find(params[:id])
  end

  # POST /directors
  # POST /directors.json
  def create
    @director = Director.new(params[:director])

    respond_to do |format|
      if @director.save
        format.html { redirect_to @director, notice: 'Director was successfully created.' }
        format.json { render json: @director, status: :created, location: @director }
      else
        format.html { render action: "new" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /directors/1
  # PUT /directors/1.json
  def update
    @director = Director.find(params[:id])

    respond_to do |format|
      if @director.update_attributes(params[:director])
        format.html { redirect_to @director, notice: 'Director was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1
  # DELETE /directors/1.json
  def destroy
    @director = Director.find(params[:id])
    @director.destroy

    respond_to do |format|
      format.html { redirect_to directors_url }
      format.json { head :no_content }
    end
  end
end

app/views/directors/_form.erb
<%= nested_form_for @director, :html => { :class => "form-horizontal" }  do |f| %>
  <% if @director.errors.any? %>
    <div id="error_explanation" class="alert alert-block">
      <h2><%= pluralize(@director.errors.count, "error") %> prohibited this director from being saved:</h2>

      <ul>
      <% @director.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.date_select :birth_date, :start_year => 1900 %>
  </div>
  <div class="field">
    <%= f.label :gender%><br />
    <%= f.select :gender, Person::VALID_GENDERS.map {|k,v| [v,k]}, :include_blank => 'Select' %>
  </div>

  <div class="field">
    <%= f.label :movies %>
    <%= f.fields_for :movies do |movie_form| %>
      <%= movie_form.select :id, Movie.all.map { |d| [d.name, d.id] }, :include_blank => "Select an movie"  %>
      <%= movie_form.link_to_remove "Remove this movie", :class => "btn btn-danger btn-mini" %>
    <% end %>
    </br>
    <p><%= f.link_to_add "Add a movie", :movies, :class => "btn btn-mini" %></p>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directors/create.html.erb
<h1>Directors#create</h1>
<p>Find me in app/views/directors/create.html.erb</p>

app/views/directors/destroy.html.erb
<h1>Directors#destroy</h1>
<p>Find me in app/views/directors/destroy.html.erb</p>

app/views/directors/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/directors/index.html.erb
<h1>Listing directors</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @directors.each do |director| %>
  <tr>
    <td><%= director.name %></td>
    <td><%= director.birth_date%></td>
    <td><%= director.gender_humanize%></td>
    <td><%= link_to 'Show', director %></td>
    <td><%= link_to 'Edit', edit_director_path(director) %></td>
    <td><%= link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Director', new_director_path , :class => "btn btn-large btn-primary disabled" %>

app/views/directors/new.html.erb
<h1>New director</h1>

<%= render 'form' %>

<%= link_to 'Back', directors_path %>

app/views/directors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @director.name %>
</p>

<p>
  <b>Birth date:</b>
  <%= @director.birth_date %>
</p>

<p>
  <b>Gender:</b>
  <%= @director.gender_humanize %>
</p>

<% if @director.movies.any? %>
<p>
  <b>Movies:</b>
  <ul>
    <% @director.movies.each do |movie| %>
      <li><%= link_to movie.name, movie %></li>
    <% end %>
  </ul>
</p>
<% end %>


<%= link_to 'Edit', edit_director_path(@director), :class => "btn btn-large" %>
<%= link_to 'Back', directors_path , :class => "btn btn-large" %>